src/Rails/config/routes.rb
PillBox::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :reminders

  resources :medications

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'
  match "/about" => "home#about"
  match "/credits" => "home#credits"

  match "/mypillbox" => "pillbox#mypillbox"
  match "/myreminders" => "pillbox#reminders"
  match "/meds_list" => "pillbox#meds_list"
  match "/coaches" => "pillbox#coaches"
  match "/buddies" => "pillbox#buddies"
  match "/settings" => "pillbox#settings"

  match 'user_root' => 'pillbox#mypillbox'

  post "/send_email_reminder/:id", :controller => "reminders", :action => "send_email_reminder"
  post "/send_text_reminder/:id", :controller => "reminders", :action => "send_text_reminder"
  post "/send_voice_reminder/:id", :controller => "reminders", :action => "send_voice_reminder"

  post "/reminder_call", :controller => "reminders", :action => "reminder_call"
  post "/directions", :controller => "reminders", :action => "directions"
  post "/goodbye", :controller => "reminders", :action => "goodbye"
end

src/Rails/app/models/reminder.rb
class Reminder < ActiveRecord::Base
  attr_accessible :date, :medication_id, :message, :user_id

  belongs_to :user
  belongs_to :medication

end

src/Rails/app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

   before_filter :authenticate_user!
  
  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reminders }
    end
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
    @reminder = Reminder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reminder }
    end
  end

  # GET /reminders/new
  # GET /reminders/new.json
  def new
    @reminder = Reminder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reminder }
    end
  end

  # GET /reminders/1/edit
  def edit
    @reminder = Reminder.find(params[:id])
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(params[:reminder])

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render json: @reminder, status: :created, location: @reminder }
      else
        format.html { render action: "new" }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reminders/1
  # PUT /reminders/1.json
  def update
    @reminder = Reminder.find(params[:id])

    respond_to do |format|
      if @reminder.update_attributes(params[:reminder])
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy

    respond_to do |format|
      format.html { redirect_to reminders_url }
      format.json { head :no_content }
    end
  end

  def send_email_reminder
    @reminder = Reminder.find(params[:id])
    @user = current_user
    PillboxMailer.reminder_email(@user, @reminder).deliver
    render :json => @reminder
   end

  def send_text_reminder
    @reminder = Reminder.find(params[:id])
    @user = current_user
    reminder_text(@user, @reminder)
    render :json => @reminder
  end

  def send_voice_reminder
    @reminder = Reminder.find(params[:id])
    @user = current_user
    reminder_voice(@user, @reminder)
    render :json => @reminder
  end

  def reminder_call
    @post_to =  "/directions"
    render :action => "reminder.xml.builder", :layout => false
  end

  def directions
    if params['Digits'] == '1'
      redirect_to :action => 'reminder_call'
      return
    end

    if params['Digits'] == '2'
      redirect_to :action => 'goodbye'
      return
    end

    @redirect_to = "/goodbye"
    render :action => "goodbye.xml.builder", :layout => false 
  end

  def goodbye
    render :action => "goodbye.xml.builder", :layout => false 
  end
end

src/Rails/app/helpers/reminders_helper.rb
module RemindersHelper
end

src/Rails/app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :medication_id %><br />
    <%= f.number_field :medication_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/Rails/app/views/reminders/edit.html.erb
<h1>Editing reminder</h1>

<%= render 'form' %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

src/Rails/app/views/reminders/index.html.erb
<h1>Listing reminders</h1>

<table>
  <tr>
    <th>Date</th>
    <th>User</th>
    <th>Medication</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reminders.each do |reminder| %>
  <tr>
    <td><%= reminder.date %></td>
    <td><%= reminder.user_id %></td>
    <td><%= reminder.medication_id %></td>
    <td><%= reminder.message %></td>
    <td><%= link_to 'Show', reminder %></td>
    <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
    <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reminder', new_reminder_path %>

src/Rails/app/views/reminders/new.html.erb
<h1>New reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', reminders_path %>

src/Rails/app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @reminder.date %>
</p>

<p>
  <b>User:</b>
  <%= @reminder.user_id %>
</p>

<p>
  <b>Medication:</b>
  <%= @reminder.medication_id %>
</p>

<p>
  <b>Message:</b>
  <%= @reminder.message %>
</p>


<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>