src/Rails/config/routes.rb
PillBox::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :reminders

  resources :medications

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'
  match "/about" => "home#about"
  match "/credits" => "home#credits"

  match "/mypillbox" => "pillbox#mypillbox"
  match "/myreminders" => "pillbox#reminders"
  match "/meds_list" => "pillbox#meds_list"
  match "/coaches" => "pillbox#coaches"
  match "/buddies" => "pillbox#buddies"
  match "/settings" => "pillbox#settings"

  match 'user_root' => 'pillbox#mypillbox'

  post "/send_email_reminder/:id", :controller => "reminders", :action => "send_email_reminder"
  post "/send_text_reminder/:id", :controller => "reminders", :action => "send_text_reminder"
  post "/send_voice_reminder/:id", :controller => "reminders", :action => "send_voice_reminder"

  post "/reminder_call", :controller => "reminders", :action => "reminder_call"
  post "/directions", :controller => "reminders", :action => "directions"
  post "/goodbye", :controller => "reminders", :action => "goodbye"
end

src/Rails/app/models/medication.rb
class Medication < ActiveRecord::Base
  attr_accessible :bottle_size, :dosage_quant, :dosage_size, :drug, :frequency,
                  :name, :notes, :period, :user_id

  belongs_to :user
  has_many :reminders

  # 2 times for reminders 9am and 6pm
  @morning = 9
  @evening = 18

  # TBC
  # returns the time of the next reminder after a given time
  def next_reminder(time)
    # return next_time
  end

  # Creates the next "num" reminders
  def create_reminders(num)
    reminders_created = false
    now = Time.now
    # if self.period == "per day"
      # if self.frequency == 1
        while num > 0
          time = 9
          now = now.tomorrow unless now.hour < time
          Reminder.create(
            date: Time.new(now.year, now.month, now.day, time).localtime, 
            user_id: self.user_id, 
            medication_id: self.id,
            message: "take #{self.dosage_quant} #{self.dosage_size} of #{self.name} at #{time}:00#{time<12 ? "AM" : "PM"}"
          )
          num -= 1
        end
        reminders_created = true
      # end
    # end
    remove_old_reminders if reminders_created
  end

private

  def remove_old_reminders
    Reminder.where("user_id = ? AND medication_id = ? AND created_at < ?", self.user_id, self.id, (Time.now - 5)).destroy_all
  end
  
end

src/Rails/app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

   before_filter :authenticate_user!
  
  # GET /medications
  # GET /medications.json
  def index
    @medications = Medication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medications }
    end
  end

  # GET /medications/1
  # GET /medications/1.json
  def show
    @medication = Medication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medication }
    end
  end

  # GET /medications/new
  # GET /medications/new.json
  def new
    @medication = Medication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medication }
    end
  end

  # GET /medications/1/edit
  def edit
    @medication = Medication.find(params[:id])
  end

  # POST /medications
  # POST /medications.json
  def create
    @medication = Medication.new(params[:medication])

    respond_to do |format|
      if @medication.save
        @medication.create_reminders(5)
        format.html { redirect_to mypillbox_url, notice: 'Medication was successfully created.' }
        format.json { render json: @medication, status: :created, location: @medication }
      else
        format.html { render action: "new" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medications/1
  # PUT /medications/1.json
  def update
    @medication = Medication.find(params[:id])

    respond_to do |format|
      if @medication.update_attributes(params[:medication])
        @medication.create_reminders(5)
        format.html { redirect_to mypillbox_url, notice: 'Medication was successfully updated.' }
        format.json { head :no_content }
      else
        @medication.create_reminders(5)
        format.html { render action: "edit" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    @medication = Medication.find(params[:id])
    @medication.destroy

    respond_to do |format|
      format.html { redirect_to medications_url }
      format.json { head :no_content }
    end
  end
end

src/Rails/app/helpers/medications_helper.rb
module MedicationsHelper
end

src/Rails/app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <%= f.hidden_field(:user_id, :value => current_user.id) %>

  <div class="field">
    <%= f.label :name, "Medication Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :drug, "Drug Name" %><br />
    <%= f.text_field :drug %>
  </div>
  <div class="field">
    <%= f.label :dosage_quant, "Dose Quantity" %><br />
    <%= f.number_field :dosage_quant %>
  </div>

  <div><%= f.label :dosage_size, "Dose Units" %><br />
  <%= f.select(:dosage_size, options_for_select([["pills", "pills"], ["scoops", "scoops"], ["shot", "shot"], ["lozenge", "lozenge"], ["other", "other"]], "pills")) %></div>

  <div class="field">
    <%= f.label "Instructions" %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

src/Rails/app/views/medications/edit.html.erb
<h1>Editing medication</h1>

<%= render 'form' %>

<%= link_to 'Show', @medication %> |
<%= link_to 'Back', medications_path %>

src/Rails/app/views/medications/index.html.erb
<h1>Listing medications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Drug</th>
    <th>Dosage quant</th>
    <th>Dosage size</th>
    <th>Frequency</th>
    <th>Period</th>
    <th>User</th>
    <th>Bottle size</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medications.each do |medication| %>
  <tr>
    <td><%= medication.name %></td>
    <td><%= medication.drug %></td>
    <td><%= medication.dosage_quant %></td>
    <td><%= medication.dosage_size %></td>
    <td><%= medication.frequency %></td>
    <td><%= medication.period %></td>
    <td><%= medication.user_id %></td>
    <td><%= medication.bottle_size %></td>
    <td><%= medication.notes %></td>
    <td><%= link_to 'Show', medication %></td>
    <td><%= link_to 'Edit', edit_medication_path(medication) %></td>
    <td><%= link_to 'Destroy', medication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medication', new_medication_path %>

src/Rails/app/views/medications/new.html.erb
<h1>New medication<%= " for: " + current_user.name if current_user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', medications_path %>

src/Rails/app/views/medications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medication.name %>
</p>

<p>
  <b>Drug:</b>
  <%= @medication.drug %>
</p>

<p>
  <b>Dosage quant:</b>
  <%= @medication.dosage_quant %>
</p>

<p>
  <b>Dosage size:</b>
  <%= @medication.dosage_size %>
</p>

<p>
  <b>Frequency:</b>
  <%= @medication.frequency %>
</p>

<p>
  <b>Period:</b>
  <%= @medication.period %>
</p>

<p>
  <b>User:</b>
  <%= @medication.user_id %>
</p>

<p>
  <b>Bottle size:</b>
  <%= @medication.bottle_size %>
</p>

<p>
  <b>Notes:</b>
  <%= @medication.notes %>
</p>


<%= link_to 'Edit', edit_medication_path(@medication) %> |
<%= link_to 'Back', medications_path %>